[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'Build completed for SmolPot Backend API'"]

[start]
cmd = "node src/server.js"